name: Base Image
run-name: Base (via ${{ github.event_name }})

on:
  push:
    branches:
      - "main"
      - "release"
    paths:
      - ".github/workflows/build-push-base.yml"
      - "base/*"
      - "docker-bake.hcl"
      - "docker-compose.yml"
      - "!**.md"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - ".github/workflows/build-push-base.yml"
      - "base/*"
      - "docker-bake.hcl"
      - "docker-compose.yml"
      - "!**.md"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository }}
  IMAGE_NAME: base
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build (CUDA)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: "Runtime"
            target: "base"
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=raw,value={{date 'YYYYMMDD'}},enable={{is_default_branch}}
              type=sha,format=short
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr

          - name: "Devel"
            target: "base-dev"
            tags: |
              type=raw,value=dev-latest,enable={{is_default_branch}}
              type=raw,value=dev-{{date 'YYYYMMDD'}},enable={{is_default_branch}}
              type=sha,format=short,prefix=dev-
              type=ref,event=branch,prefix=dev-
              type=ref,event=tag,prefix=dev-
              type=ref,event=pr,prefix=dev-

    steps:
      - name: Free disk space
        id: free-disk-space
        run: |
          df -h .
          sudo find /usr/share/dotnet -delete      # frees 20GB on the runner
          sudo find /usr/local/lib/android -delete # frees 10GB on the runner
          df -h .

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.tags }}

      - name: Dump merged docker-bake.hcl to file
        id: dump-bake
        run: |
          docker buildx bake --print \
            -f docker-bake.hcl \
            -f ${{ steps.meta.outputs.bake-file }} \
            ${{ matrix.target }} | tee docker-bake-${{ matrix.target }}.hcl

      - name: Upload metadata artifact
        id: meta-artifact
        uses: actions/upload-artifact@v3
        with:
          name: meta-${{ matrix.target }}
          path: |
            ${{ steps.meta.outputs.bake-file }}
            docker-bake-${{ matrix.target }}.hcl

      - name: Build and Push Versioned Tags
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: ${{ matrix.target }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ (github.event_name == 'push' && is_default_branch) || inputs.force-push }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
