name: xformers for NGC
run-name: xformers via ${{ github.event_name }}

on:
  push:
    branches:
      - "main"
      - "release"
    paths:
      - ".github/workflows/build-ngc-xformers.yml"
      - "docker/xformers/*"
      - "docker-bake.hcl"
      - "!**.md"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - ".github/workflows/build-ngc-xformers.yml"
      - "docker/xformers/*"
      - "docker-bake.hcl"
      - "!**.md"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-xformers
  cancel-in-progress: true

env:
  XFORMERS_REF: "v0.0.20"
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: xformers
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build (NGC)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: "NGC 23.05"
            target: "xformers"
            flavor: |
              suffix=-ngc23.05
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=schedule,pattern={{date 'YYYYMMDD-hhmm' tz='UTC'}},enable={{is_default_branch}}
              type=sha,format=short
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr

    steps:
      - name: Free disk space
        id: free-disk-space
        run: |
          df -h .
          sudo find /usr/share/dotnet -delete
          sudo find /usr/local/lib/android -delete
          df -h .

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: ${{ matrix.flavor }}
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ matrix.tags }}
            type=raw,value=${{ env.XFORMERS_REF }},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=xformers-ngc
            org.opencontainers.image.description=xformers wheel for NGC pytorch containers
            org.opencontainers.image.vendor=neggles.dev

      - name: Build & Push Image
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: ${{ matrix.target }}
          files: |
            ./docker/xformers/docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ contains(fromJSON('["push", "schedule"]'), github.event_name) || inputs.force-push }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=min
