name: Base Image
run-name: Base (via ${{ github.event_name }})

on:
  push:
    branches:
      - "main"
      - "release"
    paths:
      - ".github/workflows/build-push-base.yml"
      - "docker/base/*"
      - "docker-bake.hcl"
      - "docker-compose.base.yml"
      - "!**.md"

  workflow_dispatch:
    inputs:
      force-push:
        description: "push to GHCR"
        type: boolean
        required: true
        default: false

  pull_request:
    paths:
      - ".github/workflows/build-push-base.yml"
      - "docker/base/*"
      - "docker-bake.hcl"
      - "docker-compose.base.yml"
      - "!**.md"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-base
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository }}
  IMAGE_NAME: base
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  build:
    name: Build (CUDA)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: "Base CUDA 12.1"
            target: "base-cu121"
            flavor: |
              suffix=-cu121
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=schedule,pattern={{date 'YYYYMMDD-hhmm' tz='UTC'}},enable={{is_default_branch}}
              type=sha,format=short
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr

          - name: "Base CUDA 11.8"
            target: "base-cu118"
            flavor: |
              suffix=-cu118
            tags: |
              type=raw,value=latest,enable={{is_default_branch}}
              type=schedule,pattern={{date 'YYYYMMDD-hhmm' tz='UTC'}},enable={{is_default_branch}}
              type=sha,format=short
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr

    steps:
      - name: Free disk space
        id: free-disk-space
        run: |
          df -h .
          sudo find /usr/share/dotnet -delete
          sudo find /usr/local/lib/android -delete
          df -h .

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: ${{ matrix.flavor }}
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.tags }}

      - name: Build & Push Image
        id: build-push
        uses: docker/bake-action@v3
        with:
          targets: ${{ matrix.target }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=min
